project_id = "dr-doaa-samy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322

[storage]
enabled = true
file_size_limit = "25MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/admin"]
